name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ Feature/*, master ]
    paths: 
    - 'apis/poi/**' 
  pull_request:
    branches: [ master ]
    paths: 
    - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: apis/poi
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: apis/poi
