name: go-cd
env:
  GO111MODULE: on

on:
  workflow_dispatch:
  push:
    branches: [ master, feature/* ]
    paths:
    - '.github/workflows/go-cd.yml'
    - 'apis/trips/**'
    - "test"
  

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show
          az storage -h
          az acr build --image "devopsoh/api-trips:1" --registry openhacknd25pzl5acr --file Dockerfile . 