name: go-ci
env:
  GO111MODULE: on

on:
  workflow_dispatch:
  push:
    branches: [ feature/*, master ]
    paths:
    - '.github/workflows/go-ci.yml'
    - 'apis/trips/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/trips/**'
    - '.github/workflows/go-ci.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./tests/
