name: go-cd
env:
  GO111MODULE: on

on:
  workflow_run:
    branches: 
    - master
    workflows: 
    - go-ci 
    types:
     - completed  
  
jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/trips'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show
          az storage -h
          echo "ls before"
          ls
          cd ${GITHUB_WORKSPACE}/apis/trips
          echo "ls after"
          ls
         
          az acr build --image "devopsoh/api-trips:${GITHUB_SHA}" --registry openhacknd25pzl5acr --file Dockerfile . 

          az webapp config container set --slot openhacknd25pzl5trips-staging --name 'openhacknd25pzl5trips' --resource-group 'openhacknd25pzl5rg' --docker-custom-image-name openhacknd25pzl5acr.azurecr.io/devopsoh/api-trips:${GITHUB_SHA} --docker-registry-server-url openhacknd25pzl5acr.azurecr.io

          bash ${GITHUB_WORKSPACE}/polling.sh -i https://openhacknd25pzl5trips-staging.azurewebsites.net/api/healthcheck/trips
          echo $?