name: Go
env:
  GO111MODULE: on

on:
  workflow_dispatch:
  push:
    branches: [ feature/*, master ]
    paths:
    - '.github/workflows/go.yml'
    - 'apis/trips/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/trips/**'
    - '.github/workflows/go.yml'

jobs:

  build:

    matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...
