# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ feature/*, master ]
    paths:
    - '.github/workflows/maven.yml'
    - 'apis/user-java/**'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/maven.yml'
    - 'apis/user-java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/user-java'

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create an issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
