# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master, feature/* ]
    paths:
    - 'apis/userprofile/**'
    - '.github/workflows/node.js.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/userprofile/**'
    - '.github/workflows/node.js.yml'
jobs:

  - build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'apis/userprofile'        
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: create issue
      if: failure() # OR Check a bool variable you create and toggle as needed
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  - deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            az storage -h
            echo "ls before"
            ls
            cd ${GITHUB_WORKSPACE}/apis/userprofile
            echo "ls after"
            ls
         
            az acr build --image "devopsoh/api-userprofile:${GITHUB_SHA}" --registry openhacknd25pzl5acr --file Dockerfile . 
            az webapp config container set --name 'openhacknd25pzl5userprofile' --resource-group 'openhacknd25pzl5rg' --docker-custom-image-name openhacknd25pzl5acr.azurecr.io/devopsoh/api-trips:${GITHUB_SHA} --docker-registry-server-url openhacknd25pzl5acr.azurecr.io
